### ISSUE TITLE
Best of LMMS Judging

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms.io#160]
First of all... good work to the organizers, judges and musicians!

Some concerns have been raised this year about the judging process used in the Best of LMMS Volume 2 competition.

I wanted to start an open forum about:
 * What methods were used this year versus last year which caused questions to be raised
 * What can be done to improve this for next year

This topic has an inherent vice to stir quite a bit of emotion, so please consider each-other's feeling before posting any direct attacks or any comment based on any specific ruling.

The most valid complaint I've received was in regards to the pooling of votes for voting process.  It was brought to my attention, and confirmed via the raw voting results that of ALL of the contest winners, **only ONE TRACK received a vote rating of all 7 judges**.  This is ONE TRACK also won the competition, suggesting some tracks may not have been fairly rated as they received zero points out of default, never standing a chance against others.

Again, this is not to imply the winners weren't worthy, but rather discuss the process and if it can be improved on for our competition next year. :+1:

**Comment by Spekular** [comment]
I was just wondering about this. At first I assumed each judge had to listen to each entry. Since that could be quite a lot to listen to, I also considered that perhaps the tracks would be split between judges so that each song gets the same number of listens but the judges don't have to listen to every song. The problem I see with this is that a particular track might align well or poorly with the tastes of the judge/s they're "assigned".

Could one of the judges describe the process used this year?

**Comment by Sti2nd** [comment]
Yes! After the exams :grimacing:

**Comment by StakeoutPunch** [comment]
Before I say anything else, my main issue with the judging this year is that they rated production and creativity, but selected songs to judge based on personal preference, with really doesn't determine either. Furthermore, judges could only vote on a certain number of songs from the entire list of 104. Finally, even though artists could not have more than one song win in the final judging revision, judges were still allowed to vote on both songs from an artist. This means even more "votes" that were not available to other artists that may have had a chance otherwise.

As I created the process used last year (and was a judge along with Avelocity), I'll put it out "officially" what it was because I have heard that it has been misrepresented this go around by an internet game of telephone. The whole process can be boiled down to two steps: Determine what songs to vote on, and vote on them. However in practice it is more complex and more importantly, balanced, than it sounds. I will provide the method, then contrast it to what I know about the process used this year.

**Method in nutshell:**
Judges pick 6 songs each out of the entry pool. No duplicates, only one song per artist. This results in 36 songs, judges discuss choices (especially if two pick the same song). Then each of the 36 songs is rated by each judge. Each song may receive 0-10 in two fields: Creativity and Production. Creativity is for the melodic content, is it bland? Catchy? Overused? etc. Production is strictly for the actual sound quality. Is it mixed well? Mastering? Do elements fit well? etc. These scores are then manipulated and averaged because I am a stats junkie. Here is the spreadsheet if you would like to view the averaging in play: https://docs.google.com/spreadsheet/ccc?key=0Ao9dcRGtm8vJdEhMNTduSHRnbGZVY0lvbmdGeWMtSEE&usp=sharing

**Method comparison/explaination:**
I can't tell you how many songs there were last year, but each judge was allowed to select 6 songs each. This allows for judges to predetermine what they want to vote on at an early stage, while making sure that each song voted on gets a fair chance from each judge. Only one song per artist could be chosen, and judges could discuss the songs (for example, Second Flight and I both initially picked the same song, so one of us just chose another). In all honesty, judges really picked way more than just six songs in case the songs they wanted were picked by someone else.

One could argue that this is the same as letting the judges vote on any song like this year, because songs that aren't picked get a zero anyways. That is not true for several reasons. First, while judges were still able to choose what they wanted to vote on, those selections were pulled into one uniform list. Judges could discuss choices and critique selections. Second and more importantly, songs that were picked got the full attention of each judge. If a song was picked, it had the right of being rated by each judge, receiving uniform attention regardless of musical taste and opinion. The contest is about picking the best, and each judge may have their own opinions about what "best" is or isn't. Selectively choosing songs to vote on ahead of time and placing them in a list means that if a judge wants to vote on particular songs, they can, but the selection isn't just limited to their opinion. Having random selections of 35 by each judge just means that each judge can run "wild" and unchecked (no real form of peer control, the mother of unbiased results). It makes sense to allow a judge to pick what they want to vote on, but not if the judges aren't even voting on the same material. That is a bottleneck. If a song has the potential to be voted on, then it should receive an actual rating, not a zero because the judge "didn't like it" or "liked other songs more".

Making judges rate songs by both creativity and production seems to be about the only common element between this year and last year, and even then I have issues with the execution (but let's take a comic relief: I'm always mad about something. Always). For starters, rating a song on a scale of (0)1-3 does not even begin to capture the range of creativity and production possible. This is evidenced somewhat by one of the judges rating in decimals, effectively doubling his/her range to judge by. 0-10 is a solid range that allows for truly bad entries to get docked, while still allowing for mediocre, average, great, amazing, etc. without needing to go in to the thousandths place in decimal shenanigans. Arguably, even 0-10 is not enough, but we aren't professionals so we don't need 1-10^10 :^)

In my system the final peer control/attempt to remove bias is averaging. Averaging allows a song to have a score that reflects the judgement of each judge, and reduces the judges' ability to throw a song's score. In cumulative systems the differences in points amass rather quickly because the points are just being slapped together. Consequently this means that a judge giving scores in the extremities of the range hold more weight than it should, especially if other judges don't agree with that score. I'm looking at the ridiculous amounts of 3 point votes in this year's judging, and of course all the 0 point scores from judges not selecting a song. Yep, this year did *not* use an averaging system. However, I crunched the numbers and not having uniform judging threw my averaging system off, showing once more that judges need to vote consistently on things to get a valid group opinion. It isn't fair if one song gets a vote from every judge, but another only gets an opinion from just three.

All in all, my system had flaws, and I wouldn't use it again without some revision. However, I feel that it created a far less biased result than what happened with the judging process used this round, and hopefully I did a good enough job explaining why I think so above :>

**Comment by tresf** [comment]
Evan, thanks for your input.

@Sti2nd any feedback?

**Comment by Umcaruje** [comment]
@Sti2nd Its the end of june now, I think its time for you to finally explain the logic of this year's voting system, since I'm really not getting it.

**Comment by Sti2nd** [comment]
Yeah, should have done it ages ago. Unfortunately I think that summary is never going to happen, this is how far I got with that.

<Start of summary>
Introduction
Competitions with LMMS have been found to be popular among the community. The Best of LMMS Competition, hereby called BoL, also produces a result in form of an album which is great promotion for LMMS.

Seeing how popular BoL was last year many wanted it to happen again this year, among them me and the judges from last year. That I was among the judges this year happened because of two reasons.
1. I had been in a Skype chat with the previous judges for over two years, that is both before, under and after BoL v1. So I knew a littlebit about how they did it last year.
2. I was acting as some kind of coordinator for the community pages and community events. The first BoL was initiated by the judges themselves and I had very little to do with it. No one had stepped up and said they wanted to arrange BoL in december 2014, and so I chatted with some of the judges on Skype or G+ and we had a little discussion about how we would find the next judges, for it was clear that they would prefer to participate themselves this year. I too wanted to participate myself so I originally didn't want to judge, but I felt like I owned the judges of 14 to make the competition happen at least one more time so they could have their chance in the contest. After Christmas it seemed someone had to step up to get things going, and because of bullet point 1 I suspected I was a clear candidate. And so I offered to be one of the judges, and to gather them.


Finding judges
From my chat with two of the judges last year (and Tres) I looked for judges that was skilled, had experience with LMMS and music. Of course good is subjective, and so I asked artists that were among the best LMMS artist in my eyes. (I should perhaps mention that I know about quite a few LMMS artists having used LMMS for a long time and even written blog posts about various LMMs artists). I believe I picked judges that in general produce electronic music, wether that is a representative selection of the community or not, one can have no clue about... I feel the pick-out needs to be smarter. Apart from being good... you also need to know that the judge is genuinely interested in being a judge! (<- I didn't ask that question) I asked 6 artists first, then one more when I suspected negative answer from one of the artist I asked.  After som pursuation I had six artist plus myself. Seven artists in total. 
Idea: If people had applied for an interview instead of someone headhunting you would be sure they were interested.


Communication between judges
I don't know exactly how they communicated last year, but of course they had the Skype chat which I suppose at least some of the communication was done on. These guys had been chatting for over a year already and knew each other pretty well, for example which time zones they were in, so I suspect communicating wasn't an obstacle.

I found it really hard to communicate with the judges as a group. At first I contacted everyone on SoundCould in private messages and quickly realized that wouldn't work if we were to discuss as a group. We ended up using e-mail as that was something everyone of us had, except one judge who didn't want to join that e-mailing so I agreed he would just be notified when he was to rate the songs. My idea was that we would decide everything (rules, deadline, other stuff) together as a group, but most times only one or two judges answered. So the decisions were taken by me and one or two others. Of course everyone had a chance to have their say, but yeah, sad.

Documentation
From BoL v1 we had the rules in a google document, and I got an explanation from judges how the judging worked, got to see a google doc and the google sheet with points from BoL v1.

We ended up with keeping the rules from BoL v1. https://docs.google.com/document/d/1hycvxg3PT2sRMJV7YGHZI11jS0eHE_BGS-_hZ3elD_s/edit?usp=sharing And added two extra
* A song cooperation between a judge and yourself are not allowed.
* Users can not submit songs submitted for previous BoL competitions
All rules for BoL v2 looks like this https://docs.google.com/document/d/12DmSVkOB7eHahibjezOs0gX8i66SoOz7bggtS89hehw/edit?usp=sharing Notice that the extras-section is new.


The judging system
BoL v1. 
Round 1. The judges picked five songs each. Had to talk to each other to find five unique songs.
Round 2: Gave points to the picked songs in originality and sound design. 

BoL v2. After feedback from the judges last year that the voting system could be improved I decided to look into it. 


To consider/settle/discuss for next BoL
- Settle an ideology/winner song ideal: If the competition has a clear purpose the competition can evolve around that, and is easier to host. I suspect that last year wanted to show variety as well as quality, while this year I only encouraged to select songs they liked. This year we also encouraged (making) new music. "To honor the developers" doesn't say what kind of songs they should be honored with.
- Finding judges which have all the qualities we want them to have can be extremely hard. The qualities are however dependent on the judge system, so a judge system cannot demand more from a judge than what one can expect from an amateur musician that have used a free program for a few years, so to say... For example: BoLv1 system takes it for granted that a song a judge pick is "a good song", since it most likely will make it on the album (80% chance), so BoLv1 system demands more from a judge than a more democratic system. Democracy care less about each voters individual opinion and more about the majority.
- A suggestion has been made to not publish the winner list in the order of points, just a random order or alphabetically. BoL v1 had album in alphabetical order (except for the first song which they agreed on should be Galaxy because they all thought it was great according to the judges), BoL v2 ordered solely by points. Both years they published a list sorted by points, though. The exact scores were never published.
- A suggestion has been made to allow anyone who wants to see the voting sheets with the points.

<End of summary>

I was going to write a lot so that next BoL had something to start with... but life has stopped my involvement in LMMS I know, and it has been like that for a long time, so I'll write something now about the judging process for BoLv2.

I found the process last year to be hard to carry out since it demanded several rounds of us judges writing up names of songs on a shared document and repeating the process over and over until we had unique song names. Not a very complicated process, but hard to achieve, I thought, since I was literally picking six other different users from around the world and we weren't in the same Skype chat and couldn't talk forth and back as fast as they could in BoLv1. Communication could have worked out somehow, though. 
The reason why I decided to swap this first round of judging entirely out with another system was the fact that each song a judge selected in BoLv1 had 80% chance of being on the album, so I thought the judge had too much power over how the album would look. Cause here I am being completely honest: I didn't know if the judges I picked didn't care about composition or mixing, or was complete idiots, so to speak. How could I know that? I could only know that after the judgment. Perhaps is it I that have a really bad taste? I wanted a system that would get an ok result most people would like, "even if one of the judges were conducting sabotage" kind of :p And that a democratic voting system could be a secret ballot I looked at as another benefit of the system.

Originally it was going to be like I describe here https://docs.google.com/document/d/1HxoKtmgbFxk9oVkkOdm0Z9VHI_4ks-_ORG54Ix3xSTE/edit?usp=sharing
Since we used a really long time on the first round, though, I thought I could work something out of that first round instead of going through yet another round of judging. 
So first and only round of BoLv2 ended up like this: Each judge selected 30 songs and rated them with two numbers between 0 and 3, a judge could thus maximum give 6 points to a song. 
I did some mistakes in that round, and also found out about the unwritten rule when publishing the results, but on second try I think I succeeded.

Things that should be improved in BoLv2 system
- many songs ended up with same scores, especially from place 15 and higher. One need a way to select one of them, or make it happen more seldom. (Remember that increasing the amount of points a judge can give to a song also gives the judges more individual power).
- selecting and rating 30 songs is a lot of work, too much probably. (Remember that less songs gives the judges more individual power).

I know I did some mistakes, like including unfinished judge sheets, had to exclude one sheet in the final result - second try. I am glad I pulled the competition off finally (with a lot of help from Fastigum!) and did write something down so things might be easier next year! I am probably not becoming active here again in a long time... I still have a dream to actually code something on LMMS, so I hope that if I get back I can be of more use.

Lastly, about "all judges aren't considering all songs in BoLv2" or something like that. Well, they are just as much as round 1 in BoLv1? Yes, you can give points to a song and end up being the only judge that does that. Isn't that why democracy works? You don't get all you want, but you get most of it, or the most important (since you are setting different scores).

**Comment by tresf** [comment]
I see a lot of words, but I'm still failing to see an explanation. 

How can a song get voted on from one judge?  How does that happen?  Shouldn't all songs that are considered into the competition get voted on by all judges?

These results are simply puzzling to me and no one is trying to throw you under any bus or point any fingers, we just want to make damn sure whatever happened this year doesn't get repeated.

**Comment by tresf** [comment]
> If the competition has a clear purpose the competition can evolve around that, and is easier to host. I suspect that last year wanted to show variety as well as quality, while this year I only encouraged to select songs they liked.

The purpose is extremely clear, is it not?  The purpose is.  **To select the best songs made with LMMS**.  That is pretty simple.  This isn't a competition on ~~What songs might get on an EDM mix tape~~ or ~~What songs a judge personally likes from the competition~~, right?

> all judges aren't considering all songs in BoLv2

I don't think anyone has that expectation.  I don't remember any complaints about BoL v1, so this is just something we're trying to fix moving forward.

**Comment by grejppi** [comment]
> The reason why I decided to swap this first round of judging entirely out with another system was the fact that each song a judge selected in BoLv1 had 67% chance of being on the album, so I thought the judge had too much power over how the album would look.

But now every song had 0% chance of being on the album, except if one of the judges listened to it. The only way to increase that was to get one or more judges to listen to it.

> Cause here I am being completely honest: I didn't know if the judges I picked didn't care about composition or mixing, or was complete idiots, so to speak.

How did the judges choose this time which ones to listen to and which ones to flat-out ignore?
I'm sure you can see how the one that got most points is the only one that everyone listened to. Was it just a safe pick because Red Ambassador happens to be a bit more well known than most LMMS artists out there? Were they afraid of listening to entries from artists they had never heard of?

> Lastly, about "all judges aren't considering all songs in BoLv2" or something like that. Well, they are just as much as round 1 in BoLv1? Yes, you can give points to a song and end up being the only judge that does that. Isn't that why democracy works? You don't get all you want, but you get most of it, or the most important (since you are setting different scores).

The first round was where the judges merely picked their favourites. BoL2 judging stopped at that point. BoL1 took all other entries into consideration after the first round however.

**Comment by Sti2nd** [comment]
Yes, lot of text cause I wanted the judges next year to be able to learn from this.

Ok, so what you find to be the problem is that it is the judges personal opinion that might get the song on the album while you believe it was less so last year cause of the "originality"- and "sound design"-points?

**Comment by StakeoutPunch** [comment]
To be very blunt, that wall of text is really just a lot of fluff, extra narrative that probably isn't needed, and repeated content. Sometimes to get an idea across effectively less is more. That being said, thank you for taking the time to write it, even if it didn't answer some of our questions.

From what I can tell, the "problems" this year happened only from trying to implement new methods into the judging process, so fixing them should be as simple as reverting to using the original system of BoL1. The flaws in the original system can be fixed as well, but that would be something to work on moving forwards.

**Comment by Sti2nd** [comment]
Yeah, some of you BoLv1 judges should try to fix what you believe could be fixed :) I have already said what I didn't like about it.

**Comment by Sti2nd** [comment]
Oh, someone also ought to make a guide for arranging BoL, cause my wall of text isn't (good) enough. At least if we want each competition to be somewhat similar, or else that will be impossible.

This is a very brief list https://docs.google.com/document/d/1Wx5Hk5gObwT7euI2nuGCVcj4PDZvUbDgXrMEcOmJeCM/edit?usp=sharing

**Comment by tresf** [comment]
These issues have all been addressed in BoLv3.  Closing.
