### ISSUE TITLE
Download all presets / Download all samples in one zip file.

### ISSUE THREAD

**Issue by circuitfry** [LMMS/lmms.io#163]
Whenever someone adds to the community repository, create a zip archive of all of the synth presets and samples to be available in one download and make that archive downloadable to the public.

**Comment by tresf** [comment]
We have some limited support for what you are describing via the unpublished LSP api:

Here is a listing of everything in our database:
https://lmms.io/lsp/web_resources.php?download=index

via:
https://github.com/LMMS/lmms.io/blob/master/public/lsp/web_resources.php#L14

This could be enhanced to zip up the content and download a tarball.  This file size could get pretty large though, so we wouldn't want to abuse it (perhaps display it to signed in users only).

The LSP code is all open source, so feel free to tweak it as needed.  Toby is the original author, but I ported it to our new site, so I can help get you setup, if you know php. :)

**Comment by circuitfry** [comment]
It's been a while since I learned PHP so I can't say I'm confident in modifying the code or using it. Is there a way however to use the XML you provided me to download all of the files in one go?

**Comment by tresf** [comment]
Yeah, you could make your own download links with that info and grab each individually but it would be a lot of http requests back to the server.

**Comment by circuitfry** [comment]
Yeah now that I think about it, I'd rather not stress the site. :\ I'm afraid this will just have to be a feature request.

**Comment by Wallacoloo** [comment]
Have we looked into services like CloudFlare? They're basically a (free)
CDN.

It works by configuring one of lmms' DNS entries to point to CF's servers
and then whenever CF receives a request, it checks to see if it already has
the content and if it does, it sends the cached data directly to the user
without even one http request to lmms' server. If it doesn't have the
content, then it relays the request to lmms, caches the response according
to its e-tags (which means it will automatically cache static files for the
appropriate lifetime and discard dynamic content) and then relays that data
to the user.

It's very easy to configure - just edit one dns entry to point to CF, and
you can reverse the edit at any time if you find you don't like it. Typical
configuration is to put all static content on a subdomain like
static.lmms.io and just put that subdomain behind CF, which will save some
small amount of latency (usually only 10-20 ms in my experience) on dynamic
requests to www since they won't be tunneled through CF. But you could also
put the entire site behind CF and it would work fine.

They're a great company to work with and from my experience, they're pretty
generous with their free tier. I'm pretty sure you can get at least a few
TB/month for free. Last I used them, they didn't actually have a stated
limit and the only difference between upper-tiers was allowing things like
https tunneling, automatic js/html/css minimization and one-on-one support
with their customers.
On Jun 4, 2015 8:35 AM, "circuitfry" <notifications@github.com> wrote:

Yeah now that I think about it, I'd rather not stress the site. :\ I'm
afraid this will just have to be a feature request.

—
Reply to this email directly or view it on GitHub
<https://github.com/LMMS/lmms.io/issues/163#issuecomment-108937230>.

**Comment by tresf** [comment]
@Colin:

https://github.com/LMMS/lmms/issues/661

- Tres.Finocchiaro@gmail.com

**Comment by tresf** [comment]
Closing, as we'd have to rewrite a bunch of things to make this possible, better targeted at a new LSP rather than scabbing it onto the limited one we have.
