### ISSUE TITLE
bumping on soundcloud

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms.io#166]
I dont know if this is an 'problem', but somehow i think its a little unfair to those who does not do this. The thing is, some peeps keep pushing their tracks up in the NEW category (no clue how its done), but should we allow it, or make a rule for it?

**Comment by Umcaruje** [comment]
You can't change how soundcloud works. If someone wants to push their tracks up in the soundcloud group they can and there is nothing we can do about it. If you wonder how you do that, its easy: remove your song from a group, then add it back right away - Instant bump.

If you want, you can take that upstream to soundcloud, I don't know if they have an open issue tracker somewhere, but there should be something like that out there. 

I'm gonna close this issue out, since its not an issue with us, but with how soundcloud works.
