### ISSUE TITLE
Rethinking Documentation

### ISSUE THREAD

**Issue by Umcaruje** [LMMS/lmms.io#212]
So I wanted to write this in a while, so here it goes:
#### Our documentation is in a dire need of refreshment.
I don't think the wiki can stay as is, and I would suggest that we completely move our documentation from a mediawiki instance to something that is GitHub based.
#### Why do this?
Well currently, there is absolutely no review on what and how content is updated on the wiki. With a centralized repository with markdown files, maintaining the documentation would get a lot easier. 

Also a current problem with the documentation is varying writing style and many grammar errors that exist on the articles. With GitHub's Pull Request review function this would be much easier to manage.

Current services that I can see used to host the new documentation are https://readthedocs.org/ and https://www.gitbook.com/

Another feature that has the same function as the mediawiki is the Github online editor which can make it really easy for people not familiar with git to submit to the docs. 

We also eliminate the spam problem, which was why the wiki account creation process is not public anymore.

I also wanted to talk about streamlining the docs, currently we have many pages that can be combined together (Almost all of the `Using...` pages can be really removed and be added to the actual pages about the part of the program that's being talked about).

This is still an idea and I want to start a discussion, our documentation is very outdated at the moment, and will be even more outdated when 1.2 is out. One thing I haven't thought about is localisation, as I have no idea how that'd fit here so if @liushuyu has some ideas I'd love to hear them.

Also tagging some people for feedback @tresf @musikBear @StakeoutPunch

**Comment by tresf** [comment]
I rarely use the documentation which means I rarely read it; rarely find places which need editing.

That said I do use GItHub for docs for another technical project and I really like it.  There are some caveats to using a pure wiki, the main part is organization.

In the project which uses it successfully, we use the main GitHub landing page to drive a drop down menu.  Using standard bulleted table of contents page.   @Lukas-W coded it for this other project so that it integrates into the site nicely.  If we want to use that technique, I can send you a snapshot of the code to integrate with bootstrap.  The site was mirrored after the software stack used in LMMS so it should be pretty fast to integrate.

Each page has an edit link and just signs one into GitHub to the edit screen.  If the person doesn't have commit access, it'll automatically do a `patch-1` commit and allow a pull request like you've mentioned.  We use GItHub in the other project because it's so fast to author, preview, edit and screenshot the content.   It's also easy to find hidden documentation without having special access.

That's where my knowledge of wiki's ends.  Although I write a lot of technical documentation, I find full end-to-end user documentation to be dry and largely unused.  I only write content that I use, so I rarely touch the LMMS wiki.

**Comment by Lukas-W** [comment]
Related: [#42 (comment from August 2014)](https://github.com/LMMS/lmms.io/issues/42#issuecomment-53953428) and [Lukas-W/lmms.sfwiki](https://github.com/Lukas-W/lmms.sfwiki), a git clone of our wiki (including history) I made back then to test the idea.

**Comment by musikBear** [comment]
I link to the wiki on regular basis, as part of helping people with ordinary questions. The worst thing about the wiki imo is the outdated imagery and the lack of proper key-word search.
A new documentation should aim for a centralized imagery, where simple image replacements, would be sufficient for updating the 'wiki'/ documentation. 
*That* feature should imo be most significant  in the decision to select a specific provider/ hosting service.
Some may think -It does not matter that the images looks a bit different, but thats because we oldies *knows* what we see! A newcomer gets quite confused when the images show something different, than what he has on his screen. 
So the service with the most open and accessible image-handling gets my vote.
A final thought could be that an online documentation could be replaces with a up to date PDF for download. The benefit here would be that the user could use the PDF also offline, well he could even study it in the commuter train on any device :)

**Comment by Umcaruje** [comment]
>@Umcaruje knows if bitwigs userguide is readable, and user friendly, and if so, then we could copy that structure for our user-guide. 

Never have even looked at it lol, I should probably

P.S. @musikBear I read my github notifications through email, so whenever you edit a post I can't see that, I just get the original. When you add a lot of new stuff to your post with edits, please consider posting another comment because of us email people :wink:

**Comment by musikBear** [comment]
>  whenever you edit a post I can't see that, I just get the original. 

Oki noted 👍

**Comment by tresf** [comment]
Gitbook has some very limited contributor rules, it only allows 5 contributors.  I've emailed them with a request for an exception to the user-limit twice and they haven't replied.

I understand Gitbook has Github integration, but I'm not sure how a "Pull Request" would look.  Can contributors do a change using the nice Gitbook UI and then request the change from us?  How does this work?  Can we get around the 5-user limitation?

**Comment by allejok96** [comment]
Just chiming in here with some viewpoints, don't mind me :eyes: 
1) Please put all the documentation in **one single place** (including docs for LSP and other things if there will ever be any). The current thing with the lmms.io/documentation and lmms.io/wiki is confusing enough even if the content is the same. The former site looks nicer but....

2) Please have it in a **searchable** format. Like the later one. I don't think pure GitHub wiki is searchable in that sense. I don't want to go through a whole book to get the answer to a specific question.

3) If there will be a PDF, have it auto-generated so it always stays up to date with the online version. The worst is when there are multiple docs which all say different things.

4) **Nice editing UI** - yes please! I've never contributed to any documentation. Maybe would if I could wrap my head around it.

Docs are greatly needed for LMMS. Lowers the learning curve and makes it look more professional. Although comprehensive step by step manuals are a bit overkill imho. I just want the docs when I have a question or run into trouble.

**Comment by Umcaruje** [comment]
>Please @Umcaruje reconsider this topic.

@r-mice I simply don't have the time to commit to a full rewrite of our documentation. It's a huge project, and if you or someone you know would like to take point on this, I can help out. There was a start on writing a new 1.2 by a community member, but we haven't heard from them in months. If you would like to discuss this futher, I suggest hitting me up on the project discord: https://lmms.io/chat

**Comment by tresf** [comment]
> Please put all the documentation in one single place (including docs for LSP and other things if there will ever be any). The current thing with the lmms.io/documentation and lmms.io/wiki is confusing enough even if the content is the same. The former site looks nicer but....

It is in one place.  The `/wiki` URL was temporary until we worked out the bugs for `/documentation` but we never finished that task and we [never will](https://github.com/LMMS/lmms.io/issues/100).

> Please have it in a searchable format. Like the later one. I don't think pure GitHub wiki is searchable in that sense. I don't want to go through a whole book to get the answer to a specific question.

It is searchable at the `/wiki` url, but it sucks.  Google is better, embarrassingly but that's just the nature of using a MediaWiki instance, which we're trying to get away from.  Anyway, it's part of the replacement effort, which we have no volunteers for.

> If there will be a PDF, have it auto-generated so it always stays up to date with the online version. The worst is when there are multiple docs which all say different things.

The better replacement technologies offer this.  MediaWiki doesn't, so this is something the team strongly agrees on, but does not have the ability to offer until the replacement occurs.

> Nice editing UI - yes please! I've never contributed to any documentation. Maybe would if I could wrap my head around it.

Same as above.  Replacement will offer this if we can get our hands on one that allows the contributor base that we need.  Shuffling around 1 login to the "volunteers of the week" is OK too, I guess.  We were hoping for a sponsorship from [GitBook](https://www.gitbook.com/@lmms) but never heard back.  $35/month for 5 users is quite high just for documentation.

So opinions on this topic are OK, but what we really need is volunteers to run with it -- something anyone can start anytime.

**Comment by tresf** [comment]
Just came across this thread on GitBook's GitHub tracker... https://github.com/GitbookIO/gitbook/issues/1808

**Comment by tresf** [comment]
AaronO had his email in there, so I'm trying to reach out to him directly.  Hopefully he reads and replies to our sponsorship request. 🤞

**Comment by tresf** [comment]
Aaron said yes.  Let's stack some resources there and see how it pans out.  one of us will update this thread once the sponsorship goes through.

**Comment by tresf** [comment]
Formal FOSS request submitted.  Still nothing back from GitBook on whether or not we are approved but I can grant access to anyone willing to run with this.  @PhysSong already said he would be willing to work on it.

**Comment by tresf** [comment]
GitBook finally approved our sponsorship request and claim that our sponsored account is now active.  The project needs someone to help manage this new home for documentation.  If not already involved, please come over to `#devtalk` channel here: https://discordapp.com/invite/PruNxpG and tell us who you are!  We should be able to build content immediately with the right help.  Thanks for the patience.

**Comment by liushuyu** [comment]
I think this thread is now most stale since GitBook documentation has replaced MediaWiki instance.

Closing. Feel free to reopen if necessary.
