### ISSUE TITLE
Spam control

### ISSUE THREAD

**Issue by zonkmachine** [LMMS/lmms.io#220]
There's been persistent flood spamming in the forum.
My suggestion is to enforce first post moderation.

We could also activate the StopForumSpam function of the Ban Hammer extension that is already in place.

**Comment by musikBear** [comment]
Yes i have 'hammered' i think 5-6 spammers these last 8 day or so. It is ok from my pov to enforce first post moderation. I already send all first posters to a *Welcome-post*, so it would not be an issue to verify them as legit users. @zonkmachine

**Comment by tresf** [comment]
> I already send all first posters to a Welcome-post,

What the hell is this?

> Yes i have 'hammered' i think 5-6 spammers these last 8 day or so

I changed the questions around a bit, has it helped in the past 2 days?

**Comment by zonkmachine** [comment]
> I changed the questions around a bit, has it helped in the past 2 days?

Looks like it. At least there was no flood attack last night.

**Comment by tresf** [comment]
Board upgraded to 3.2.0, reCaptcha installed.

![image](https://cloud.githubusercontent.com/assets/6345473/24490727/ed90b4b0-14f1-11e7-9246-e9e3b280246b.png)

Note, @Umcaruje the 3.2 build is not backwards compatible with 3.1 themes, so I had to wipe the styles and plugins.

 * ComBoot 3.2-beta is installed but the logo/footer changes from 3.1 need to be ported over.  Files are located in `~/backups/forum_3.1.3`.
 * Reminder @Lukas-W had originally setup [`master/forum/style/template`](https://github.com/LMMS/lmms.io/tree/master/forum/style/template) so we could use symlink replacements for our theme files.  If we aren't using this technique anymore, we should remove the orphaned files.

**Plugin that are no longer installed**

![image](https://cloud.githubusercontent.com/assets/6345473/24490813/517b1bfa-14f2-11e7-8bdb-f2a30baab03e.png)

**Comment by Umcaruje** [comment]
Thanks @tresf I'll get to the theme changes as soon as I find time.

**Comment by musikBear** [comment]
> has it helped in the past 2 days?

There has not been any attacks i know of last 2 days
If a pammer get past the check, i am sorry to see that the *ban hammer* extension has been removed, but it will ofcause not matter if the new improved control works.

**Comment by tresf** [comment]
> i am sorry to see that the ban hammer extension has been removed

Did you use this feature?  Banning through ACP is still possible with one click.

This extension lists 3.1.3 as highest supported version (we're on 3.2 now) and I'm not sure who installed it to begin with.    If we need it, I'll reactiviate since  [users reporting that it works fine with 3.2](https://www.phpbb.com/customise/db/extension/ban_hammer_2/support/topic/170781).  Just let me know.

**Comment by musikBear** [comment]
>  Banning through ACP is still possible with one click.

Im not sure my rights include that option. 
Do not even know what the acronym stand for
The only way i have been able to remove all posts from a spammer, has been with the *banHammer* addOn.
This is my options in the small-menu
![modoption1](https://cloud.githubusercontent.com/assets/6662066/24547815/0650e92c-1612-11e7-9f67-b82846b6951e.JPG)

These are the options in the Moderator window:
![modoption2](https://cloud.githubusercontent.com/assets/6662066/24547858/3c742ad2-1612-11e7-9186-64cf9c4485ce.JPG)

I have manually removed post by post, but that is seriously tedious, especially when the spammer then dump 25 more on you, as you are doing it :p  

I miss being able to 
* 'pin' posts
* remove all posts and the poster in one hit -eg banHammer

...Would you believe....
The very moment i write there is a spam attack 👎

**Comment by tresf** [comment]
Ok, we'll reinstall it then.

ACP = Administrative Control Panel.  No, you don't have access.

**Comment by tresf** [comment]
@musikBear it's reinstalled.  How do I know it's working?

**Comment by tresf** [comment]
Also @zonkmachine the phpBB boards seem to suggest the Q&A is the only effective method.  I don't understand this.  Is the "I'm not a robot" reCaptcha not as good as it claims?  Should we revert back?

**Comment by musikBear** [comment]
> it's reinstalled. How do I know it's working?

@tresf I dont know what you re-installed, so i cant answer if it is working. there is no ban-hammer option on a user right now.
 reCaptcha with that 'im not a robot' is imo weak, the option on wiki, where you need to read and answer a math-question (q&a), or those that relies on a picture of letters, that the user need to repost as ascii inputs, they are imo better, but not watertight

**Comment by tresf** [comment]
> there is no ban-hammer option on a user right now.

I  just reinstalled the plugin from scratched and enabled everything except ban IP.  Does this help at all or is it still broken?  I can't find anything about the compatibility of this plugin with 3.2 except a [single thread on the phpBB forums stating "seems to work fine"](https://www.phpbb.com/customise/db/extension/ban_hammer_2/support/topic/170781).

Side not... @musikBear DON'T EDIT POSTS UNNECESSARILY or your moderator access will be removed.  This is your second warning.

![image](https://cloud.githubusercontent.com/assets/6345473/24581921/df4478c6-16f2-11e7-8225-69203add5d2d.png)

**Comment by tresf** [comment]
> reCaptcha with that 'im not a robot' is imo weak

I don't care about your opinion, I only care about what works.  If the spam keeps coming in, then the reCaptcha is no better than the previous captcha.  I'll work on re-installing the Q&A captcha.

**Comment by tresf** [comment]
> I'll work on re-installing the Q&A captcha.

Q&A captcha re-enabled.  Please let me know in a few days if this is helping.

**Comment by musikBear** [comment]
> Side not... @musikBear DON'T EDIT POSTS UNNECESSARILY or your moderator access will be removed. This is your second warning.

You had NOT used his quote, so he would NOT know that you asked him a question. I HELPED you and added a ping to the post. 
Btw nice.. to know that you do not care about my opinion

**Comment by Lukas-W** [comment]
> Btw nice.. to know that you do not care about my opinion

I'm sure @tresf is not ignoring your opinion in particular, but is just saying that when discussing things like effective anti-spam techniques, personal opinions are generally irrelevant and add no value to the discussion.

**Comment by tresf** [comment]
> You had NOT used his quote,

It is not tkye

**Comment by tresf** [comment]
> You had NOT used his quote, so he would NOT know that you asked him a question

It is no your role to rewrite the internet.  Moderator's jobs are to step in and help control the forums, not to blast welcome spam and edit every conversation.  Stay out of the posts.  If you are going to argue and not comply, we'll skip the third warning and pull access now.  You decide.

Please answer my question about ban-hammer.  AFAIK you're the only one that uses this plugin.

**Comment by musikBear** [comment]
not working
![image](https://cloud.githubusercontent.com/assets/6662066/24608330/68b7bc92-1876-11e7-8864-1136510e8b52.png)
@tresf

**Comment by tresf** [comment]
> not working

So you're saying that bringing back the questions hasn't helped?  I'm not sure what else to do...

1. reCaptcha should have solved this 100%, but it didn't
2. The questions are only a week-old.  The bots shouldn't have learned them already.

![image](https://cloud.githubusercontent.com/assets/6345473/24611279/8fa337a4-184f-11e7-967d-8db950571c3c.png)

> No banhammer. 40+ pages spam.

I thought I was clear, this plugin was never written for 3.2.  If you can research an alternative, we can install it.

> You are the reason people leave

Please don't start a flame war.  Editing people's posts is unacceptable.   The only time we do this is when the posts is otherwise unreadable (the devs do this in GitHub bug reports in special situations like adding a screenshot to a top post, wrapping non-code text in code tags).  We use it sparingly and we put *Edited by @foo, added bar*.

Your quote clobbering is superfluous.  You attack people for not using quotes and you edit quote.  GTFO of the posts unless necessary.

> I leave as mod Clean up yourself!
 
We do have others with ACP access that can help with this problem.  If you can stop eding posts, we'll restore your access.

**Comment by tresf** [comment]
The ban hammer plugin has been disabled since it does not appear to be compatible with 3.2.

The last 1,500+ spam posts were from two IP addresses, so I've banned them and I'm looking at moderating new users from posting too many times in the first x days.

I'm reopening this issue since spam in the forums is still a problem.

**Comment by tresf** [comment]
> Thanks @tresf I'll get to the theme changes as soon as I find time.

@Umcaruje FYI, I've done the bare-minimum changes to remove comboot jumbotron and bring our logo back via:  https://github.com/LMMS/lmms.io/commit/ba2f610f72bfcb24296f22844a7d950809e3fab7

Thus restoring @Lukas-W's symlink technique... 

```
navbar_header.html -> ../../../../../forum/style/template/navbar_header.html
overall_footer.html -> ../../../../../forum/style/template/overall_footer.html
overall_header.html -> ../../../../../forum/style/template/overall_header.html
```

**Comment by musikBear** [comment]
>  If you can stop eding posts unnecessarily, we'll restore your access.

What do you mean 'restore access' ?
I *left*! 
Nothing to restore here.
> I don't care about your opinion, I only care about what works

a remark like that is properly the most insulting a **lead** can make.
I would have left, even if i was a paid employee.

I pméd Brandy, so he can take care of spam, which are abundant, also right now.

**Comment by tresf** [comment]
> I don't care about your opinion, I only care about what works

> > a remark like that is properly the most insulting a lead can make.

Because you're taking it out of context.  The plugin isn't available, so it really doesn't matter how bad you want it.  I cannot weigh your desire against the impossible.  The impossible wins.  If this is upsetting, perhaps you should research the differences between [objective and subjective arguments](http://utminers.utep.edu/omwilliamson/engl1312/subjective.htm).

> I left! Nothing to restore here.

Sorry, you are correct.  I noticed that only after writing it.

> I pm'd Brandy, so he can take care of spam, which are abundant, also right now.

Thanks.  I'm open to other suggestions as well.  Even as far as writing some logging statements in the bulletin board code to see where the point of entry is.

On a personal note... With no evidence of an attempt to correct this problem by any other party (including you, @musikBear) by means of researching plugins, contacting the php users groups, etc, it's disheartening from my perspective to see the time invested into this upgrade go unappreciated by the most active user.  Perhaps an offline conversation should happen to mend any feelings along the way so if you get on Discord, I'd be happy to talk.

**Comment by tresf** [comment]
I've been banning the recent IPs associated with spam attacks and this has been ok for about a week.  We'll continue to monitor.

**Comment by zonkmachine** [comment]
78 posts...
![78posts](https://cloud.githubusercontent.com/assets/6368949/24954030/e6c88400-1f7d-11e7-9fab-4ef48847c64f.png)

Now can we have first post moderation?

**Comment by tresf** [comment]
> Now can we have first post moderation?

Adding daily, human process to a technical problem is bad for all parties involved, but if it helps the spam, knock yourself out.

**Comment by tresf** [comment]
Here are some workarounds that require modification of the phpBB source code... Interesting article because many apply to us...

https://www.michel-kraemer.com/5-anti-spam-measures-for-phpbb3/

**Comment by zonkmachine** [comment]
On the Linuxmint forum, where I was a moderator for some two years or so, I think first post moderation was the only thing that worked. Unfortunately I don't have time to read up on administration so I'm not going to change anything on the forum. I can drive by and remove spammers once in a week or so but that's about it for the time being.

**Comment by tresf** [comment]
I've spent another hour researching this and it appears our questions may be too easy to solve, so I've made them more challenging.

Hopefully this helps.

![image](https://cloud.githubusercontent.com/assets/6345473/24972049/fabfd602-1f87-11e7-8f6f-7a553caa031b.png)

**Comment by liushuyu** [comment]
>I've spent another hour researching this and it appears our questions may be too easy to solve, so I've made them more challenging.
>
>Hopefully this helps.

I think some of the questions are too specific to one culture... Maybe more LMMS related...
I've seen many websites use its own product spec for the question, I suppose we could do that as well.

**Comment by tresf** [comment]
You get to refresh up to 5 times.  Please be specific and we can change.

**Comment by liushuyu** [comment]
>You get to refresh up to 5 times. Please be specific and we can change.

Question 1, 2, 5 and 6 are fine to me, they are (general) common sense.
3 and 8 need some English skills, while 7, although I know the answer, but I think if you don't know the answer, you will also not know how to search for the answer, since this festival is not a common one in other parts of the world.

**Comment by tresf** [comment]
Q4 allows multiple answers.  For example cold water, hot tea are all valid.

The difficulty is 100% intentional.  The easy questions were allowing bots to get through.  The St Patrick's one can be removed if you think it's bad.   We can add more too if you have some proposals.

**Comment by liushuyu** [comment]
>The difficulty is 100% intentional.

I know you are trying to make harder questions.

>Q4 allows multiple answers. For example cold water, hot tea are all valid.

Some people will come up with coffee/milk/chocolate/latte etc 😄 

>We can add more too if you have some proposals.

Like "Which platform do LMMS put all translate work on?" and I think this will guide human user to read our wiki, it's a better approach, isn't it?

**Comment by tresf** [comment]
> "Which platform do LMMS put all translate work on?" 

Standard users won't ever get that one. :/. Open to more suggestions though.

> Some people will come up with coffee/milk/chocolate/latte

Coffee and milk are valid but chocolate is a good addition.

**Comment by liushuyu** [comment]
>Standard users won't ever get that one. :/. Open to more suggestions though.

Okay... I am now realized it's really difficult to come up with  a question that is both "LMMS related" and "to answer the question, efforts should be made". 😃

**Comment by musikBear** [comment]
Well..

Open the lmms-wiki and browse to the page **Project Menu**.
Questions: 
1) What 2 formats can LMMS projects be saved as _____ _____
2) One of these formats are similar to what common filetype ________
3) In LMMS you can create "standard-projects", what are they called ________
4 Witch 2 sound-formats can LMMS export ______  ______
5) What LMMS export-file type is compressed _______
Open the wiki-page **"Plugins"**
Questions:
6) What LMMS plugin resembles the iconic TB303 bass? ________
7) What LMMS plugin is an emulator of Yamaha YM3812 _________
8) What LMMS plugin is an additive organ synthesizer ________

not that hard
Im on the other hand is too stupid to answer what form a speaker has, since 'speakers' both can be the electronic component *and* the finished store product, and some may start *their* day with a cup of scotch ..

**Comment by tresf** [comment]
This isn't a research paper, this is a sign up for our forums.  If a question require reading our antiquated wiki, we've failed.  This is a spam bot countermeasure. 

> not that hard
> Im on the other hand is too stupid to answer what form a speaker has, since 'speakers' both can be the electronic component and the finished store product,

Box, circle and round are all acceptable.

> some may start their day with a cup of scotch

Scotch is not an acceptable answer.

**Comment by musikBear** [comment]
> This isn't a research paper

I here advised a perfectly sane and useful way to stop the spam.

**Comment by tresf** [comment]
> I here advised a perfectly sane and useful way to stop the spam.

No, you provided a way to force people to a dated wiki.  The ideas are not going to be implemented, sorry.

**Comment by tresf** [comment]
I'd like to add a personal note as well... You've withdrawn your moderator status so I see your investment in this to be moot.  If you decide you want to help with the problem (versus complain about it), let us know.  Otherwise you're just complaining.

**Comment by Umcaruje** [comment]
We recieved another massive spam attack. I reinstated the sortables captcha, which now has 720 * 3 possible combinations rather than 30 * 3 so it should work well now. Only time will tell

**Comment by tresf** [comment]
Thanks.  I'm starting to think humans are breaking this, not robots.  :/

**Comment by musikBear** [comment]
Happened again 
FYI

**Comment by Umcaruje** [comment]
Looks like the  solution is to just move away from phpBB to a better forum
platform like discourse or flarum. There really are holes in phpbb's
security.

**Comment by musikBear** [comment]
@Umcaruje 
> Looks like the solution is to just move away from phpBB to a better forum platform like discourse or flarum. There really are holes in phpbb's security.

But if the spammer takes his time creating 3 or 4 new accounts, and then just start 'some' spamming-tool, then it would not matter what forum was used. Not even a blocking of several accounts on same IP within an hour or so would matter. He can still use that one account to spam any forum with 500 new chineese (?) offerings

**Comment by Umcaruje** [comment]
https://www.stopforumspam.com/ seems like something worth trying, they have a huge database.

**Comment by musikBear** [comment]
> StopForumSpam 

👍 Looks good. I cant find any negative reports 
-not on trustpilot though, but that could be because it is a free service

**Comment by musikBear** [comment]
@Umcaruje 
fyi new attack

**Comment by Umcaruje** [comment]
Yeah sorry life's been busy didn't get around implementing the extension,
will try to get into it asap

On 26 Apr 2017 12:37, "musikBear" <notifications@github.com> wrote:

@Umcaruje <https://github.com/Umcaruje>
fyi new attack

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/LMMS/lmms.io/issues/220#issuecomment-297345943>, or mute
the thread

**Comment by tresf** [comment]
They were all from the same IP.  `222.3.61.73`.  Cleaned up for now.

**Comment by musikBear** [comment]
@Umcaruje ...again 👎 
I simply cant CANT understand spamming!
WHO tf clicks on it, outside mental institutions ?! -And why lmms?!

**Comment by Umcaruje** [comment]
Installed the stopforumspam extension
we'll see how that goes

**Comment by Umcaruje** [comment]
Doesn't really help, we got hit again today

**Comment by musikBear** [comment]
Nahh the spammer makes 2 or 3 account manually, and then he start an attack tool, so he is 'legit' user, but abuses his legitimise state. Difficult to fight. 
If you could prewend users to make more than 1 new topic pr/ minute, or maybe 5 min, then it **could** be that either his tool wont work, or he will select a less protected forum.. idk

**Comment by musikBear** [comment]
@Umcaruje Sorry, but again
at least 500 posts. Looks like he has used 7 new accounts, and that they alternate through the attack.

**Comment by Umcaruje** [comment]
It's usually around 300 posts per account. This has been happening daily, but I remove them pretty quickly.

**Comment by musikBear** [comment]
@Umcaruje 
it is daily now, and also today -New attack :/

**Comment by tresf** [comment]
Open invite for those that can help.

https://lmms.io/forum/viewtopic.php?f=4&t=25436

**Comment by musikBear** [comment]
@Umcaruje new attack, im afraid B.r

**Comment by tresf** [comment]
This issue seems to have subsided.  Closing.
