### ISSUE TITLE
ambiguous statement in Code-convention

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms.io#298]
an expression used all through in https://github.com/LMMS/lmms/wiki/Coding-Conventions
is ambiguous.
Example  
> Header Guards
Header guards MUST NOT begin with an underscore _.

MUST NOT does not express that this is _prohibited_
"Must not" means "It is not absolutely necessary". 
The expression here would logically be "Must never.." or "Should never" -even "Cant..".
I dont mean to nitpick, but since LMMS is an international project, ambiguous sentences will confuse readers

**Comment by liushuyu** [comment]
Sorry, but this is not the correct repository to talk about this issue. Please direct this issue to https://github.com/LMMS/lmms/issues/new

**Comment by musikBear** [comment]
@liushuyu It is the correct repository, it is not a program-issue, its a documentation issue
https://github.com/LMMS/lmms/issues/new is for bugs in the program. This place is for everything in regards to the documentation, and this is a *documentation* issue, namely the text-guide for code-conventions.
If it does not belong here, i cant see any where it does belong.

**Comment by liushuyu** [comment]
>@liushuyu It is the correct repository, it is not a program-issue, its a documentation issue https://github.com/LMMS/lmms/issues/new is for bugs in the program. This place is for everything in regards to the documentation, and this is a documentation issue, namely the text-guide for code-conventions.

I am not going to argue about which repository is the absolutely correct one to report the issue. 
But the reality is that if you report the issue in this repository I doubt anyone who is responsible for the https://github.com/LMMS/lmms/wiki the wiki page is going to see it since they expect those issues to be in LMMS/lmms (the logic is that GitHub Wiki does not belong to `lmms.io`, it's __not__ the Wiki on `lmms.io`).

And you can see that other GitHub Wiki related issues have been proposed: https://github.com/LMMS/lmms/issues?q=is%3Aissue+wiki

**Comment by musikBear** [comment]
@liushuyu Im not going to argue at all -il move the post :)
