### ISSUE TITLE
Broken link to LMMS Tested VST Database

### ISSUE THREAD

**Issue by maidentaiwan** [LMMS/lmms.io#329]
On the page http://linuxsynths.com/vstsynths.html, the link "LMMS Tested VST Database" (https://lmms.io/documentation/Tested_VSTs) produces a 404 error.

**Comment by Spekular** [comment]
This page has moved to [MediaWiki](https://lmms.io/wiki/index.php?title=Tested_VSTs) and later been archived, so it will no longer be maintained. As of 1.2 broken VSTs are the exception rather than the norm. In addition, we've moved our documentation to docs.lmms.io.

The author of linuxsynths is free to update their page as they see fit to accommodate these changes, but there's nothing to be done on the LMMS side IMO. @LMMS/website-developers, close this?

**Comment by tresf** [comment]
@maidentaiwan per @Spekular's comments, please ask the author of that website to link to https://lmms.io/wiki/index.php?title=Tested_VSTs for now with an asterisk/disclaimer that this list is no longer maintained.
