### ISSUE TITLE
Comment count on LSP displaying number of ratings

### ISSUE THREAD

**Issue by Monospace-V** [LMMS/lmms.io#353]
On the LMMS sharing platform, the comment count displayed is off.

![image](https://user-images.githubusercontent.com/76674645/208230583-655127c3-9114-4670-a691-3e4e9d5c9ece.png)
_Displaying 6 comments_

![image](https://user-images.githubusercontent.com/76674645/208230629-47560318-d5de-4ca3-a345-6283589b87ce.png)
_Only two comments present_

It depicts number of ratings instead of number of comments, at the moment.
The file I referred to was https://lmms.io/lsp/?action=show&file=18821, one of my own, but this is obvious on any file with comments and ratings. If there are 0 comments, though, then number shown is 0 regardless of rating.

**Comment by tresf** [comment]
The SQL that's being executed is this:

```sql
SELECT files.id, licenses.name AS license,size,realname,filename,users.login,
		categories.name AS category,subcategories.name AS subcategory,
		insert_date,update_date,description,files.downloads AS downloads,
		COUNT(comments.file_id) AS comments,
		COALESCE(AVG(ratings.stars), 0) AS rating,
		COUNT(ratings.id) AS rating_count FROM files 
		INNER JOIN categories ON categories.id=files.category 
		INNER JOIN subcategories ON subcategories.id=files.subcategory 
		INNER JOIN users ON users.id=files.user_id 
		INNER JOIN licenses ON licenses.id=files.license_id 
		LEFT JOIN comments ON comments.file_id=files.id 
		LEFT JOIN ratings ON files.id=ratings.file_id 
WHERE files.id = 18821
		GROUP BY files.id ORDER BY files.insert_date DESC
```

Which is being counted by the line(s):

```sql
COUNT(comments.file_id) AS comments,
... 
LEFT JOIN comments ON comments.file_id=files.id 
```

When I run this through SQL, this is what I get... 

| id    | license                  | size | realname  | filename                | login     | category | subcategory | insert_date         | update_date         | description  | downloads | comments | rating | rating_count |
|------- |-------------------------- |------ |----------- |------------------------- |----------- |---------- |------------- |--------------------- |--------------------- |-------------- |----------- |---------- |-------- |-------------- |
| 18821 | No Rights Reserved (CC0) | 3019 | Monospace | Grand synth-y piano.xpf | Monospace | Presets  | Piano       | 2021-06-26 11:54:18 | 2021-06-26 11:56:42 | ...          |      1574 |        6 | 4.6667 |            6 |

.. so the `comments` are definitely being calculated incorrectly in the SQL statement. 

I'm sure the fix is obvious but I'm having a hard time spotting it.

**Comment by tresf** [comment]
... and the `comments` table directly:

```sql
SELECT COUNT(file_id) AS comments FROM comments WHERE file_id = 18821;
```

| comments |
|-----------|
|        2         |

**Comment by tresf** [comment]
Hmmm... it looks like a side-effect of `JOIN`.

Using a subquery fixes it... I don't know if this is the right way to tackle this problem... 

```sql
SELECT files.id, licenses.name AS license,size,realname,filename,users.login,
		categories.name AS category,subcategories.name AS subcategory,
		insert_date,update_date,description,files.downloads AS downloads,
				(SELECT COUNT(file_id) FROM comments WHERE file_id=files.id) AS comments,
		COALESCE(AVG(ratings.stars), 0) AS rating,
		COUNT(ratings.id) AS rating_count FROM files 
		INNER JOIN categories ON categories.id=files.category 
		INNER JOIN subcategories ON subcategories.id=files.subcategory 
		INNER JOIN users ON users.id=files.user_id 
		INNER JOIN licenses ON licenses.id=files.license_id 
		LEFT JOIN comments ON comments.file_id=files.id 
		LEFT JOIN ratings ON files.id=ratings.file_id 
WHERE files.id = 18821
		GROUP BY files.id ORDER BY files.insert_date DESC
```
