### ISSUE TITLE
Search function in forum

### ISSUE THREAD

**Issue by Sti2nd** [LMMS/lmms.io#51]
Right now there is no easy way to find the search function in the forums, but it exists. If you click one of the four buttons at the top, you come to a site where you can click on a button saying "return to advanced search", and thus finding the search function.
![image](https://cloud.githubusercontent.com/assets/6373430/4175967/3e3f001e-35ee-11e4-9993-5fe34afcfaaf.png)

However it is widely known that the search function in phpbb, quote: "sucks dead bears". 
![image](https://cloud.githubusercontent.com/assets/6373430/4175978/efdfc394-35ee-11e4-9b55-afacd0b7339a.png)
So what about adding a google search instead? Here is a post on how. https://www.phpbb.com/community/viewtopic.php?f=46&t=1344605#p12679825

**Comment by musikBear** [comment]
google 'site' search then
site:http://lmms.io/forum/ "piano"
But users need to know

**Comment by tresf** [comment]
For now just click a forum and use the search bar.  We need to bring this back to the main page.  The google instructions are fine for now if they work or we can make a search box that does exactly as you are describing.

**Comment by tresf** [comment]
Search is back, but our menu bar is gone.  This is largely due to the fact that our menu bar and phpBB's menu bar utilize the same space and bootstrap techniques.  Closing as resolved for now.

If someone has the ambition to hack `overall_header.html` again (and for every-single theme update), we'll happily accept it.

![image](https://cloud.githubusercontent.com/assets/6345473/13885775/79a992e8-ed0a-11e5-9b81-779e842b3973.png)

**Comment by Umcaruje** [comment]
Yeah, and when comboot comes out of the closed beta, we should maintain a fork over on the organisation, so anyone can contribute to the theme. :+1:
